export enum ErrorType {
  APP_ERROR = 'APP_ERROR',
  UNKNOWN_SERVER_ERROR = 'UKNOWN_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN'
}
